import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import AppSidebar from "@/components/elements/appsidebar";
import Player from "@/components/elements/player";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} font-sans h-screen flex flex-col antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute='class'
          enableSystem
          defaultTheme="system"
          disableTransitionOnChange>
          <div className="flex flex-col h-screen">
            <div className="flex-1 overflow-hidden">
              <SidebarProvider>
                <AppSidebar />
                <SidebarInset className="pb-20"> {/* Add padding at bottom for player */}
                  {children}
                </SidebarInset>
              </SidebarProvider>
            </div>
            <div className="w-full z-10">
              <Player />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
} 