import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/appsidebar";
import Player from "@/components/player";

const inter = Inter({

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute='class'
          enableSystem
          defaultTheme="system"
          disableTransitionOnChange>
            <SidebarProvider>
              <AppSidebar />
              {children}
            </SidebarProvider>
              <Player />
        </ThemeProvider>
      </body>
    </html>
  );
}
