[package]
name = "pulsewave-codec"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
zstd = {version = "0.13.3", features = ["wasm", "bindgen"]}
